build:
  image: framgia/laravel-workspace
  commands:
    - sleep 10
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - composer install
    - npm install
    - gulp
    - cp .env.testing .env
    - php artisan migrate --database=mysql_test
    - vendor/bin/phpunit
compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
publish:
  docker:
    storage_path: /drone/docker
    registry: antic.website:5000
    when:
      branch: develop
    email: s1rxploit@gmail.com
    repo: framgia/laravel-cd-demo
    file: Dockerfile.staging
    tag: staging
  docker:
    storage_path: /drone/docker
    registry: antic.website:5000
    when:
      branch: [master, release]
    email: s1rxploit@gmail.com
    repo: framgia/laravel-cd-demo
    file: Dockerfile.production
    tag: latest
deploy:
  rancher:
    url: http://rancher.kingofweed.top
    access_key: EE1F9AA6A7EBF7CA1C38
    secret_key: DQUneeM2YTjJdJ6wKWjhXPYxRY4aT8NAoyUZa7tT
    service: RANCHER_SERVICE_STAGING
    docker_image: antic.website:5000/framgia/laravel-cd-demo:staging
    when:
      branch: develop
  rancher:
    url: http://rancher.kingofweed.top
    access_key: EE1F9AA6A7EBF7CA1C38
    secret_key: DQUneeM2YTjJdJ6wKWjhXPYxRY4aT8NAoyUZa7tT
    service: RANCHER_SERVICE_PRODUCTION
    docker_image: antic.website:5000/framgia/laravel-cd-demo:latest
    confirm: true
    when:
      branch: [master, release]
cache:
  mount:
    - .git
    - vendor
    - node_modules
    - /drone/docker
