FROM framgia/laravel
ENV DB_HOST=localhost DB_DATABASE=demo DB_USERNAME=root DB_PASSWORD=root
COPY . /var/www/html
RUN service mysql start \
    && cp .env.production .env \
    && mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE CHARACTER SET utf8;" \
    && chmod -R 777 storage \
    && chmod -R 777 bootstrap/cache \
    && php artisan migrate --force
